data_path: data/movielens_sample.csv

data_cleaning:
  fill_missing: mean
  outlier_method: zscore

balancing:
  enable: true
  method: random

split:
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

pre_process:
  method: user_activity   # user_activity | item_popularity

in_process:
  enable: true
  method: negative_sampling   # none | regularization | negative_sampling

post_process:
  enable: true

model:
  name: MF                  # MF | LightGCN
  latent_dim: 64
  n_layers: 3               # used by LightGCN
  learning_rate: 0.01
  epochs: 10
  batch_size: 256
  device: auto              # "auto" uses cuda if available
  reg_weight: 1e-3
  neg_alpha: 0.8            # fairness sampling alpha (0..1)

evaluation:
  topk: 20