data_path: data/movielens_sample.csv

data_cleaning:
  fill_missing: mean
  outlier_method: zscore

balancing:
  enable: true
  method: random

split:
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1

pre_process:
  method: user_activity   # user_activity | item_popularity

in_process:
  enable: true
  method: negative_sampling   # none | regularization | negative_sampling
  enable_ugf: true           # UGF开关
  lambda_ugf: 0.2            # 公平-质量权衡（越大越强调公平）
  tau: 0.7                   # softmax 温度（越小越接近硬排序）
  use_js_divergence: true    # false 时改用 L2
  beta_user_personalization: 0.0   # 先用全局目标（个性化就调到 0.1）
  target_mix: {popular: 0.6, unpopular: 0.4}
  # -------------------------- 评分偏差约束：配置 --------------------------
  enable_rating_bias_constraint: true  # 是否启用评分偏差约束
  alpha_bias: 1.2                     # 约束宽松度（建议1.0-1.5）
  beta_bias: 0.5                      # 偏移量（建议0.3-0.7）
  lambda_bias: 0.1                    # 约束强度（建议0.05-0.2，越大约束越严）
  # ------------------------------------------------------------------------

post_process:
  enable: true

model:
  name: MF                  # MF | LightGCN
  latent_dim: 64
  n_layers: 3               # used by LightGCN
  learning_rate: 0.01
  epochs: 10
  batch_size: 256
  device: auto              # "auto" uses cuda if available
  reg_weight: 1e-3
  neg_alpha: 0.8            # fairness sampling alpha (0..1)

evaluation:
  topk: 20
