# ==== 数据路径 ====
# Path to the dataset CSV file
data_path: data/movielens.csv

# ==== 数据清洗参数 ====
# Parameters for data cleaning
data_cleaning:
  fill_missing: mean          # 缺失值填充方式（mean, median, zero） | Method for filling missing values
  outlier_method: zscore      # 异常值检测方法（zscore 或 iqr）   | Method for outlier detection

# ==== 数据平衡方法 ====
# Method for dataset balancing
balancing:
  method: random              # 可选方法（random, smote, cleaning+sampling, cluster） | Method to balance dataset

# ==== 降维配置 ====
# PCA configuration
dimension_reduction:
  enable: false               # 是否启用 PCA 降维             | Whether to apply PCA
  n_components: 10            # 保留的主成分数量（如果启用）  | Number of PCA components to keep

# ==== 特征处理配置 ====
# Feature preprocessing (e.g., standardization)
feature_processing:
  numeric_columns: ["age"]    # 需要标准化的数值字段列表 | List of numeric fields to standardize

# ==== 数据划分比例 ====
# Train/validation/test split ratios
split:
  train_ratio: 0.8            # 训练集比例 | Training set ratio
  val_ratio: 0.1              # 验证集比例 | Validation set ratio
  test_ratio: 0.1             # 测试集比例 | Test set ratio

# ==== 模型配置 ====
# Model configuration
model:
  name: MF                    # 模型名称（MF 或 LightGCN）| Model type: MF or LightGCN
  latent_dim: 64              # 嵌入维度 | Latent embedding size
  learning_rate: 0.01         # 学习率 | Learning rate
  epochs: 20                  # 训练轮数 | Number of training epochs
  batch_size: 256             # 批大小 | Batch size for training
